apiVersion: v1
kind: Service
metadata:
  name: webstork-service
  namespace: nex-system
spec:
  type: NodePort
  selector:
    name: nginxz
#  clusterIP: None
  ports:
  - name: metricark # Actually, no port is needed.
    port: 8282
    nodePort: 30000
    targetPort: 8282
  - name: prometheus # Actually, no port is needed.
    port: 9090
    nodePort: 30001
    targetPort: 9090
  - name: grafana # Actually, no port is needed.
    port: 80
    nodePort: 30002
    targetPort: 80
  - name: alertmanager # Actually, no port is needed.
    port: 8081
    nodePort: 30003
    targetPort: 8081
  - name: promlens # Actually, no port is needed.
    port: 8080
    nodePort: 30004
    targetPort: 8080
  - name: promsacle # Actually, no port is needed.
    port: 9201
    nodePort: 30005
    targetPort: 9201
  - name: pushgateway # Actually, no port is needed.
    port: 9091
    nodePort: 30006
    targetPort: 9091
  - name: zxzkr # Actually, no port is needed.
    port: 30003
    nodePort: 30303
    targetPort: 30003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nex-system
  name: nginxz
  labels:
    name: nginxz
spec:
  selector:
    matchLabels:
      name: nginxz
  template:
    metadata:
      labels:
        name: nginxz
    spec:
      serviceAccountName: nexc
      containers:
      - name: nginxz
        image: nexclipper/webstork:nginx-alpine-01
        #command: ['bash', '-c', '/entrypoint.sh']
        ports:
        - containerPort: 8081
        - containerPort: 80
        - containerPort: 8282
        - containerPort: 9090
        - containerPort: 8080
        - containerPort: 9201
        - containerPort: 9091
        - containerPort: 30003
