apiVersion: v1
kind: Service
metadata:
  labels:
    name: ws-alertmanager
  name: ws-alertmanager
  namespace: nex-system
spec:
  ports:
  - port: 8081
    name: alertmanager
    protocol: TCP
    targetPort: 80
  selector:
    name: webstork
  type: ${EXPOSETYPE}
