apiVersion: v1
kind: Service
metadata:
  labels:
    name: webstork-grafana
  name: webstork-grafana
  namespace: nex-system
spec:
  ports:
  - port: 80
    name: grafana
    protocol: TCP
    targetPort: 80
  externalName: nc-grafana.nexclipper.svc.cluster.local
  type: ${EXPOSETYPE}
