apiVersion: v1
kind: Service
metadata:
  labels:
    name: ws-grafana
  name: ws-grafana
  namespace: nex-system
spec:
  ports:
  - port: 80
    name: grafana
    protocol: TCP
    targetPort: 80
  selector:
    name: webstork
  type: ${EXPOSETYPE}
