apiVersion: v1
kind: Service
metadata:
  labels:
    name: ws-metricark-api
  name: ws-metricark-api
  namespace: nex-system
spec:
  ports:
  - port: 9000
    name: metricark-api
    protocol: TCP
    targetPort: 9000
  selector:
    name: webstork
  type: ${EXPOSETYPE}
