apiVersion: v1
kind: Service
metadata:
  labels:
    name: ws-prometheus
  name: ws-prometheus
  namespace: nex-system
spec:
  ports:
  - port: 9090
    name: prometheus
    protocol: TCP
    targetPort: 9090
  selector:
    name: webstork
  type: ${EXPOSETYPE}
