apiVersion: v1
kind: Service
metadata:
  labels:
    name: ws-pushgateway
  name: ws-pushgateway
  namespace: nex-system
spec:
  ports:
  - port: 9091
    name: pushgateway
    protocol: TCP
    targetPort: 9091
  selector:
    name: webstork
  type: ${EXPOSETYPE}
